Feat/fixed income flow
notuslabs/wallet-app pull request #16
Opened 2023-11-29 12:31 UTC by Tiago138

## Why

Createa a way for users to invest in RWA.

## Changes

- [x] New feature (non-breaking change which adds functionality)

1. create invest rwa screens.

2023-11-29 14:27 UTC, An-dz requested changes

2023-11-29 14:27 UTC, An-dz commented on src/components/accordion/AssetAcordion.tsx
> +const yeild = 300;
*yield

2023-11-29 14:27 UTC, An-dz commented on src/hooks/useWitdrawFiat.tsx
> +        error: "It was not possible to execute your transaction",
Should it not be in Portuguese like the rest of the application?

2023-11-29 14:27 UTC, An-dz commented on src/screens/balanceWithdrawal/WithdrawAddress.tsx
> +                  address="0xa95f25a649C83b7D1d3E4Af644C20D3d8BD8Ddb7"
Magic variable? Not sure if that's just a mock for testing.

2023-11-29 14:27 UTC, An-dz commented on src/screens/Asset/tabs/Informations.tsx
> +              paddingBottom: 80
Should use the variables to build the number, otherwise the value will be wrong if design changes. If Hermes is smart enough the JIT will compile to a constant.

2023-11-29 14:30 UTC, Tiago138 commented on src/screens/balanceWithdrawal/WithdrawAddress.tsx
> +                  address="0xa95f25a649C83b7D1d3E4Af644C20D3d8BD8Ddb7"
It is just a mock for testing.

2023-11-29 14:40 UTC, nicholascostadev requested changes

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/AmountInput.tsx
> +}: WithdrawAmountProps) {
This type should match the name of the component followed by `Props`

```suggestion
}: AmountInputProps) {
```

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/Asset/ConfirmRWA.tsx
> +type SendTransactionType = {
Again, **you don't have to change if you don't agree with me!**, but I would remove the suffix `Type`

```suggestion
type SendTransactionOptions = {
```

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/Asset/ConfirmRWA.tsx
> +  const { sendTransaction } = useInvestRWA();
I would reorganize this file by letting all hooks on top, then the rest

```suggestion
  const [transactionRespose, setTransaciontRespose] = useState<
    string | undefined
  >();

  const [investCurrency, setInvestCurrency] = useAtom(amountInputAtom);

  const selectedCurrency = useAtomValue(amountInputAtom);

  const { sendTransaction } = useInvestRWA();
  
  // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // callbacks
  const handlePresentModalPress = useCallback(async () => {
    bottomSheetModalRef.current?.present();
  }, []);
  
  const assetInfo = backedAssets[asset as keyof typeof backedAssets];
```

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/SelectCurrency.tsx
> +export type SelectCurrencyEventType = {
Same thing about the suffix `Type`, I guess it's not needed here, it's an event type. Even javascript does not use it when defining event types, some examples:

1. `CustomEvent`
2. `MouseEvent`
3. `FormEvent`
4. ...

```suggestion
export type SelectCurrencyEvent = {
```

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/SelectCurrency.tsx
> +export type OnSelectCurrencyEvent = object;
On the same file, you are not using the `Type` suffix

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/TransactionSuccess.tsx
> +export default function TransactionSucess({
It should be "Success" with 2 "c"

```suggestion
export default function TransactionSuccess({
```

2023-11-29 14:40 UTC, nicholascostadev commented on src/screens/TransactionSuccess.tsx
> +type ConfirmProps = {
It should follow the pattern of name and `Props`

```suggestion
type TransactionSuccessProps = {
```

2023-11-29 14:40 UTC, nicholascostadev commented on src/hooks/useWitdrawFiat.tsx
This file should be `useWithdrawFiat` not `useWitdrawFiat`

2023-11-29 15:22 UTC, Tiago138 commented on src/components/accordion/AssetAcordion.tsx
> +const yeild = 300;
This is only for testing, will be removed when real data comes in.

2023-11-29 17:37 UTC, jonyreis commented on src/components/accordion/AssetAcordion.tsx
> +  console.log("height", heightValue.value);
![coxinha](https://github.com/notuslabs/wallet-app/assets/35041924/8304064a-0f79-4e42-bccb-bc52059fccb0)

2023-11-29 17:51 UTC, jonyreis commented on src/screens/Asset/tabs/Details.tsx
> +          {Object.entries(productDetails || {}).map(([k, v]) => (
I would use Key to K and Values to V

2023-11-29 18:02 UTC, Tiago138 commented on src/screens/Asset/tabs/Details.tsx
> +          {Object.entries(productDetails || {}).map(([k, v]) => (
This is just a mock, so no need to change.

2023-11-29 19:15 UTC, Tiago138 commented on src/app/(app)/(modals)/fixedIncome.tsx
>    const setPage = (page: number) => pagerRef.current?.setPage(page);
I add two functions nextPage and previousPage using the currentScreen estate that I was getting from the onPageSelected event.

2023-11-29 19:15 UTC, Tiago138 commented on src/app/(app)/(modals)/withdraw.tsx
>    const setPage = (page: number) => pagerRef.current?.setPage(page);
I add two functions nextPage and previousPage using the currentScreen estate that I was getting from the onPageSelected event.

2023-11-29 19:21 UTC, jonyreis approved these changes
LGTM

2023-11-29 19:49 UTC, nicholascostadev requested changes

2023-11-29 19:49 UTC, nicholascostadev commented on src/hooks/useWithdrawFiat.tsx
> +type GetBalanceType = {
Same thing about the suffix "Type", I saw that you removed on the ones I said, so you should remove it here too

```suggestion
type GetBalanceOptions = {
```

2023-11-29 19:49 UTC, nicholascostadev commented on src/screens/balanceWithdrawal/WithdrawAddress.tsx
> +  const [transactionRespose, setTransaciontRespose] =
This has lots of typos

```suggestion
  const [transactionResponse, setTransactionResponse] =
```

2023-11-29 19:59 UTC, nicholascostadev commented
I want to add a comment, when using all uppercase texts, you should style it via CSS, not by typing. "ALL UPPERCASE"

### Why
Some screen readers read uppercase texts letter by letter, and I know sometimes that is not what you want. I know that from a web perspective, I don't know specially about mobile apps screen readers, but I guess it is also true for some bad screen readers, so you should style those uppercase texts with CSS and not by typing.

2023-11-30 14:26 UTC, Tiago138 commented
> I want to add a comment, when using all uppercase texts, you should style it via CSS, not by typing. "ALL UPPERCASE"
> ### Why
> 
> Some screen readers read uppercase texts letter by letter, and I know sometimes that is not what you want. I know that from a web perspective, I don't know specially about mobile apps screen readers, but I guess it is also true for some bad screen readers, so you should style those uppercase texts with CSS and not by typing.

I will do some research on it.

2023-11-30 14:32 UTC, nicholascostadev requested changes
You just forgot to rename the setter

2023-11-30 14:44 UTC, Tiago138 commented on src/screens/balanceWithdrawal/WithdrawAddress.tsx
> +  const [transactionResponse, setTransaciontRespose] =
:(

2023-12-02 16:28 UTC, An-dz approved these changes

2023-12-06 13:01 UTC, merged