Feat/small fixes
notuslabs/wallet-app pull request #18
Opened 2023-12-14 21:23 UTC by Tiago138

## Why

Add deposit pix, and refactored some components to fit new figma desing.

## Changes

- [x] New feature (non-breaking change which adds functionality)

- Add deposit pix
- Change deposit and withdraw flux
- Change invest asset flux

2023-12-14 22:00 UTC, nicholascostadev requested changes

2023-12-14 22:00 UTC, nicholascostadev commented on src/screens/balanceWithdrawal/WithdrawMethod.tsx
> +export type SelectMethodEvent = {
I've noticed that you have multiple exports from this same variable, mabe put it on a parent or utils file.

2023-12-15 12:07 UTC, Tiago138 commented on src/app/(app)/(modals)/withdraw/index.tsx
> +    router.push(`/withdraw/${type}` as `http${string}`);
Because it gives a type error :(

2023-12-15 13:26 UTC, Tiago138 commented on src/app/(app)/(tabs)/_layout.tsx
> +            onPress={() => router.push("/settings/")}
The expo router types wants the /

2023-12-15 13:28 UTC, Tiago138 commented on src/app/(app)/settings/index.tsx
> +import ChequeIcon from "@assets/icons/cheque.svg";
That's how it came from figma.

2023-12-15 13:29 UTC, Tiago138 commented on src/screens/DepositMethod.tsx
> +            description="Lorem ipsum alea jacta est habeas corpus omnia et bovis et omnia"
I don't have a text.

2023-12-15 13:33 UTC, Tiago138 commented on src/screens/Asset/ConfirmWithdrawRWA.tsx
> +            <Label size="md-bold">Sending Transaction...</Label>
Not gonna change since the design team need to make a proper loading screen.

2023-12-15 17:41 UTC, Tiago138 commented on src/screens/balanceWithdrawal/WithdrawMethod.tsx
> +export type SelectMethodEvent = {
I will look have a better look at it later.

2023-12-15 17:46 UTC, Tiago138 commented on src/screens/DepositPix.tsx
> +  const watchAmount = watch("amount");
It is the name of the input, so no need for this.

2023-12-18 11:06 UTC, nicholascostadev approved these changes
LGTM

2023-12-18 13:41 UTC, An-dz requested changes

2023-12-18 13:41 UTC, An-dz commented on src/screens/DepositMethod.tsx
> +            description="Faça depósitos rapidamente em reais utilizando o Pix."
Esta ordem me parece fazer mais sentido:
```suggestion
            description="Faça depósitos em reais rapidamente utilizando o Pix."
```

2023-12-18 13:41 UTC, An-dz commented on src/screens/DepositPix.tsx
> +  const watchAmount = watch("amount");
You might want to change it into a constant to be used on both places so it's clear they are tied.

2023-12-18 13:41 UTC, An-dz commented on src/app/(app)/(tabs)/(investments)/products.tsx
> +      <ListButton onPress={() => router.push("/fixedincome/")}>
I would recommend to change routes into some global constant so they can be more easily replaced. But no need to do it now.

2023-12-18 14:29 UTC, Tiago138 commented on src/app/(app)/(tabs)/(investments)/products.tsx
> +      <ListButton onPress={() => router.push("/fixedincome/")}>
The routes are type safe, so I don't know if it will be need in the future.

2023-12-18 16:30 UTC, An-dz approved these changes

2023-12-18 19:41 UTC, merged