Refactor/components
notuslabs/wallet-app pull request #8
Opened 2023-11-06 20:32 UTC by Tiago138

## Why

Changes to make the style of the code more consistent and some bug fixes.

## Changes

Changed interfaces to types.
Changed icons imports to have Icons at the end of the name.
Changed Label component to be able to change the font weight.
Changed paragraph props to be consistent with Label size props.
Fix carrousel of wallets not going to the end of the screen.
Add place holder screens for transfer and convert.
Add fonts to design tokens file.

- [x] Bug fix (non-breaking change which fixes an issue)

2023-11-06 20:48 UTC, Bmullerc approved these changes
LGTM

2023-11-07 14:11 UTC, nicholascostadev requested changes
I guess you should rename the font names like I said, other than that, it's all great and 100% better than before

2023-11-07 14:11 UTC, nicholascostadev commented on src/components/typography/Label.tsx
Generics are cool and I wanted to share that you could in fact refactor it to use a generic to generate some bits of these variants like this:

```ts
type BoldAndRegular<TSize extends string> = `${TSize}-${'bold' | 'regular'}`
type Size = BoldAndRegular<'lg' | 'md' | 'sm' | 'xs'>
// ^ -> "lg-bold" | "md-bold" | "sm-bold" | "xs-bold" | "lg-regular" | "md-regular" | "sm-regular" | "xs-regular"
```

2023-11-07 14:11 UTC, nicholascostadev commented on src/constants/DesignTokens.ts
> +};
I would refactor it to use underline instead of dashes, it's better to be accessed when using its object
```suggestion
export const fonts = {
  "PlusJakartaSans_Regular": "PlusJakartaSans_400Regular",
  "PlusJakartaSans_Bold": "PlusJakartaSans_700Bold"
};
```
With that, you could access it like `fonts.PlusJakartaSans_Regular` instead of `fonts["PlusJakartaSans-Regular"]` like you're doing right now.

2023-11-07 15:00 UTC, ChristanDaniel approved these changes

2023-11-07 17:27 UTC, merged